import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar/page";
import Store from "../providers/Store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Store>
          <div className="bg-gradient-to-b from-[#001856] via-[#007ADD] to-[#00CADA] min-h-screen">
            <Navbar />
            <div className="min-h-[calc(100vh-97px)]">{children}</div>
          </div>
        </Store>
      </body>
    </html>
  );
}
